language: python
python: 3.6

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

script:
  - coverage run -m pytest ultimanager_api

after_success: codecov
