---
# Django App Config

app_name: ultimanager-api
app_package: ultimanager_api

app_repo: 'https://github.com/cdriehuys/ultimanager-api'

app_required_packages:
  - libpq-dev

django_requirements: "{{ django_project }}/requirements/production.txt"
django_secret_key: "{{ vault_django_secret_key }}"
django_settings_module: ultimanager_api.production_settings

django_databases:
  default:
    ENGINE: django.db.backends.postgresql_psycopg2
    NAME: "{{ db_name }}"
    USER: "{{ db_user }}"
    PASSWORD: "{{ db_password }}"
    HOST: localhost
    PORT: 5432

django_manage_commands:
  - collectstatic --noinput


# NGINX Config

nginx_socket: 'http://{{ gunicorn_socket_unix }}'

nginx_site_servers:
  # Redirect from HTTP to HTTPS
  - listen: 80
    name: "{{ inventory_hostname }}"
    extra_params: |
          return 301 https://$server_name$request_uri;

  - name: "{{ inventory_hostname }}"
    listen: 443 ssl http2
    extra_params: |
          ssl_dhparam /etc/ssl/certs/dhparam.pem;

          location = /favicon.ico {
              access_log off;
          }

          location /static/ {
            alias {{ django_static_root }}/;
          }

          location / {
              include proxy_params;
              proxy_pass {{ nginx_socket }};
          }
