---
- hosts: webservers
  gather_facts: no

  become: yes
  become_user: root
  remote_user: ansible

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}-vault.yml

  roles:
    - cdriehuys.django-app
    - cdriehuys.nginx
